#pragma once

// Icons
#define IDI_APPICON             101

// Dialogs
#define IDD_SETTINGS            201

// Settings dialog controls
#define IDC_TAB_SETTINGS        1000
#define IDC_COMBO_POSITION      1001
#define IDC_COMBO_THEME         1002
#define IDC_EDIT_THICKNESS      1003
#define IDC_SPIN_THICKNESS      1004
#define IDC_EDIT_MAXBTNW        1005
#define IDC_SPIN_MAXBTNW        1006
#define IDC_EDIT_MINBTNW        1007
#define IDC_SPIN_MINBTNW        1008
#define IDC_CHECK_MIDDLECLICK   1009
#define IDC_CHECK_RIGHTCLICKGAP 1010
#define IDC_CHECK_SHOWCLOCK     1011
#define IDC_EDIT_TIMEFMT        1012
#define IDC_EDIT_DATEFMT        1013
#define IDC_EDIT_CLOCKW         1014
#define IDC_SPIN_CLOCKW         1015
#define IDC_LBL_POSITION        1016
#define IDC_LBL_THEME           1017
#define IDC_LBL_THICKNESS       1018
#define IDC_LBL_MAXBTNW         1019
#define IDC_LBL_MINBTNW         1020
#define IDC_LBL_TIMEFMT         1021
#define IDC_LBL_DATEFMT         1022
#define IDC_LBL_CLOCKW          1023
#define IDC_LBL_TOKENS          1024
#define IDC_LBL_TIMEFONTSIZE    1025
#define IDC_EDIT_TIMEFONTSIZE   1026
#define IDC_SPIN_TIMEFONTSIZE   1027
#define IDC_LBL_DATEFONTSIZE    1028
#define IDC_EDIT_DATEFONTSIZE   1029
#define IDC_SPIN_DATEFONTSIZE   1030
#define IDC_LBL_TIMECOLOR       1031
#define IDC_BTN_TIMECOLOR       1032
#define IDC_LBL_DATECOLOR       1033
#define IDC_BTN_DATECOLOR       1034
#define IDC_LBL_LINESPACING     1035
#define IDC_EDIT_LINESPACING    1036
#define IDC_SPIN_LINESPACING    1037

// Taskbar background right-click menu item IDs
#define IDM_SETTINGS            301
#define IDM_ABOUT               302
#define IDM_CLOSE_TASKBAR       303
#define IDM_REBUILD_ICON_CACHE  304
#define IDM_RESTART             305

// Task button right-click menu item IDs
#define IDM_OPEN_NEW_WINDOW     401
#define IDM_PIN_UNPIN           402
#define IDM_CLOSE_WINDOW        403

// App Menu settings tab controls
#define IDC_LBL_APPMENU_LAYOUT      1100
#define IDC_COMBO_APPMENU_LAYOUT    1101
#define IDC_LBL_APPMENU_WIDTH       1102
#define IDC_EDIT_APPMENU_WIDTH      1103
#define IDC_SPIN_APPMENU_WIDTH      1104
#define IDC_LBL_APPMENU_MAXHEIGHT   1105
#define IDC_EDIT_APPMENU_MAXHEIGHT  1106
#define IDC_SPIN_APPMENU_MAXHEIGHT  1107
#define IDC_LBL_APPMENU_ENTRYH      1108
#define IDC_EDIT_APPMENU_ENTRYH     1109
#define IDC_SPIN_APPMENU_ENTRYH     1110
#define IDC_LBL_APPMENU_GRIDCOLS    1111
#define IDC_EDIT_APPMENU_GRIDCOLS   1112
#define IDC_SPIN_APPMENU_GRIDCOLS   1113
#define IDC_LBL_APPMENU_GRIDROWS    1114
#define IDC_EDIT_APPMENU_GRIDROWS   1115
#define IDC_SPIN_APPMENU_GRIDROWS   1116
#define IDC_LBL_APPMENU_LISTFS      1117
#define IDC_EDIT_APPMENU_LISTFS     1118
#define IDC_SPIN_APPMENU_LISTFS     1119
#define IDC_LBL_APPMENU_GRIDFS      1120
#define IDC_EDIT_APPMENU_GRIDFS     1121
#define IDC_SPIN_APPMENU_GRIDFS     1122
#define IDC_LBL_APPMENU_MARGIN      1123
#define IDC_EDIT_APPMENU_MARGIN     1124
#define IDC_SPIN_APPMENU_MARGIN     1125
#define IDC_LBL_APPMENU_PADDING     1126
#define IDC_EDIT_APPMENU_PADDING    1127
#define IDC_SPIN_APPMENU_PADDING    1128

// App Menu behavior controls
#define IDC_CHECK_APPMENU_FLATTEN_SUBMENUS  1136
#define IDC_CHECK_APPMENU_FLATTEN_ALL       1137

// App Menu Sidebar controls
#define IDC_CHECK_APPMENU_SIDEBAR           1129
#define IDC_LBL_APPMENU_SIDEBARW           1130
#define IDC_EDIT_APPMENU_SIDEBARW          1131
#define IDC_SPIN_APPMENU_SIDEBARW          1132
#define IDC_CHECK_APPMENU_SIDEBAR_EXPLORER 1133
#define IDC_CHECK_APPMENU_SIDEBAR_SETTINGS 1134
#define IDC_CHECK_APPMENU_SIDEBAR_POWER    1135
